db_host: 172.17.0.2
db_name: synapse
db_user: synapse
db_password: bla
rooms:
  "!DiclCxVWHMlYHqBKpo:yolops.net": posay
  "!oFIxPyehofhbclgSfP:yolops.net": testing
output_directory: /tmp/test
log_level: INFO
daemon_interval: 10
